import {
  AlertTriangle,
  ArrowUpDown,
  BadgeInfo,
  CheckCircle2,
  ChevronRight,
  LayoutDashboard,
  Loader2,
  LogOut,
  PawPrint,
  Search,
  Settings,
  ShoppingCart,
  Tag,
  Trash,
  User,
  UsersRound,
  X,
  XCircle,
} from 'lucide-react';

export const Icons = {
  spinner: Loader2,
  closeIcon: X,
  user: User,
  tag: Tag,
  warning: AlertTriangle,
  error: XCircle,
  success: CheckCircle2,
  settings: Settings,
  info: BadgeInfo,
  arrowUpDown: ArrowUpDown,
  search: Search,
  trash: Trash,
  LayoutDashboard,
  ChevronRight,
  ShoppingCart,
  UsersRound,
  PawPrint,
  LogOut,
};
